# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" , "Lab_4_Changes"]
  pull_request:
    branches: [ "main", "Lab_4_Changes" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
#         source-url: https://nuget.pkg.github.com/CyanKingRS/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: dotnet build MeallyApp
    - name: Test
      run: dotnet test
#     - name: Create the package
#       run: dotnet pack --configuration Release MeallyApp
#     - name: Publish the package to GPR
#       run: dotnet nuget push MeallyApp/bin/Release/*.nupkg
